import "../styles/globals.css";
import { Inter } from "next/font/google";
import { Providers } from "@/Providers";
import Header from "@/components/HeaderElements/Header/Header";
import Footer from "@/components/Footer/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Apple store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <Providers> <Header />{children}   <Footer /> </Providers>

      </body>
    </html>
  );
}
